### ISSUE TITLE
Plugin does not work even though it is loaded

### ISSUE THREAD

**Issue by makakam83** [adi-itgg/FJetpack2Reloaded#1]
I've installed https://www.spigotmc.org/resources/fjetpack2reloaded.107883/ and when I write the command /fj2r give (my_username) jetpack I get "Jetpack didn't exist" Why?

**Comment by adi-itgg** [comment]
> I've installed https://www.spigotmc.org/resources/fjetpack2reloaded.107883/ and when I write the command /fj2r give (my_username) jetpack I get "Jetpack didn't exist" Why?

can you share configuration jetpack.yml?
the id is sensitive case

**Comment by makakam83** [comment]
Thanks for your reply,

Please bear with me as I'm new to this, I haven't made any changes to this file:

https://pastebin.com/ew4sNZuq

**Comment by adi-itgg** [comment]
> Thanks for your reply,
> 
> Please bear with me as I'm new to this, I haven't made any changes to this file:
> 
> https://pastebin.com/ew4sNZuq

uhhhh, i see jetpack is not the id. VIP is the id (you can use tab for auto completions)

try
`/fj2r give (your_username) VIP 125`
or
`/fj2r give (your_username) VIP`
and also you can enter arguments randomly like this
`/fj2r give 125 VIP (your_username)`
`/fj2r give VIP (your_username) 125`

**Comment by adi-itgg** [comment]
just remember # is comment

**Comment by makakam83** [comment]
Thank you, that worked.
I have another question though: I'm using this server: https://jamesachambers.com/minecraft-java-bedrock-server-together-geyser-floodgate/
Your plugin works when I connect with Java version but when I connect from a Bedrock version I can't enable the jetpack with "sneak" button even though I can obtain the jetpack and wear it. Can something be done in order for it to work in Bedrock too?

**Comment by makakam83** [comment]
EDIT: I restarted the container once again and it started working in Bedrock too :) Thanks

What command to get only fuel?

**Comment by adi-itgg** [comment]
Okay, see here [README.md](https://github.com/adi-itgg/FJetpack2Reloaded/blob/master/README.md)
