### ISSUE TITLE
add support itemsadder

### ISSUE THREAD

**Issue by Zarkness2** [adi-itgg/FJetpack2Reloaded#3]
add support for itemsadder to be able to create jetpacks with textures

**Comment by Zarkness2** [comment]
Hi, a question, what is the difference between this version and the previous one that was made in kotlin? @adi-itgg

**Comment by adi-itgg** [comment]
@Zarkness the difference about
- Smaller size and also not conflicting with any plugins
- Bugs fix (like jetpack not detect correctly when player detach the jetpack)
- More features (support all items not only armors)

**Comment by Zarkness** [comment]
> @Zarkness the difference about
> 
> * Smaller size and also not conflicting with any plugins
> * Bugs fix (like jetpack not detect correctly when player detach the jetpack)
> * More features (support all items not only armors)

okey, apart from that feature and the one I suggested, have you thought of any other feature? I can think of one that would be to be able to choose what type of fly you want the jetpack to have, either the current one or the one you control it with the mouse, which would be the one of this plugin https://www.spigotmc.org/resources/jetpack-1-7-1-14.42781/

**Comment by Zarkness2** [comment]
> @Zarkness the difference about
> 
> * Smaller size and also not conflicting with any plugins
> * Bugs fix (like jetpack not detect correctly when player detach the jetpack)
> * More features (support all items not only armors)

okey, apart from that feature and the one I suggested, have you thought of any other feature? I can think of one that would be to be able to choose what type of fly you want the jetpack to have, either the current one or the one you control it with the mouse, which would be the one of this plugin https://www.spigotmc.org/resources/jetpack-1-7-1-14.42781/
@adi-itgg

**Comment by Zarkness2** [comment]
hello @adi-itgg ??

**Comment by Zarkness** [comment]
@adi-itgg hello?

**Comment by Zarkness2** [comment]
@adi-itgg

**Comment by adi-itgg** [comment]
> > @Zarkness the difference about
> > 
> > * Smaller size and also not conflicting with any plugins
> > * Bugs fix (like jetpack not detect correctly when player detach the jetpack)
> > * More features (support all items not only armors)
> 
> okey, apart from that feature and the one I suggested, have you thought of any other feature? I can think of one that would be to be able to choose what type of fly you want the jetpack to have, either the current one or the one you control it with the mouse, which would be the one of this plugin https://www.spigotmc.org/resources/jetpack-1-7-1-14.42781/ @adi-itgg

next feature

**Comment by adi-itgg** [comment]
> add support for itemsadder to be able to create jetpacks with textures

can you describe this, need more information because i didn't use itemsadder plugin

**Comment by adi-itgg** [comment]
> add support for itemsadder to be able to create jetpacks with textures


@Zarkness can you describe this, need more information because i didn't use itemsadder plugin

**Comment by Zarkness2** [comment]
> > add support for itemsadder to be able to create jetpacks with textures
> 
> @Zarkness can you describe this, need more information because i didn't use itemsadder plugin

instead of putting that it is a vanilla item, put that it is an item of the itemsadder, but if you have already added the custommodeldata, it should still work.

but if you add support to itemsadder for the textures it would be easier since you would only have to put ia: <id_item_itemsadder>, instead of putting the custommodeldata.
