### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by DaanKrivaan** [adi-itgg/FJetpack2Reloaded#4]
Sometimes I have to restart my server because certain group cannot use jetpack. They get "[FJetpack2Reloaded] You don't have permission!". They have permissions granted in LuckPerms.
Its the first time Im posting anything here so if you need any more details, Ill provide as much as I can get :)

**Comment by adi-itgg** [comment]
please provide more detailed information, such as server version, server type and how the bug appeared. is it when the player relogin or what?

> Sometimes I have to restart my server because certain group cannot use jetpack. They get "[FJetpack2Reloaded] You don't have permission!". They have permissions granted in LuckPerms. Its the first time Im posting anything here so if you need any more details, Ill provide as much as I can get :)

**Comment by hinoraito** [comment]
Same issue here. 
Version:1.20.1
server type; paper 
Using luckperms.

I was able to narrow the problem down. It appears that when people take the jetpack off and put any other chestplate/elytra on and then switch back to the jetpack it gives them the message of no permission,

**Comment by GGxSHADOWxYT** [comment]
To add on to Hinoraito,

We were able to get it working once.  Once we all got off the night and back in next day we couldnt use them again.  It is telling us that we have no perms to use them.  We tried restarting but it still would not work properly

**Comment by AlecMcCutcheon** [comment]
I'm having the same issue on 1.19.4, paper, luckyperms. I've noticed that if I set the player to op then they toggle their jetpack and then I deop them they can use the jetpack again.

**Comment by AlecMcCutcheon** [comment]
This issue basically makes the plugin unusable without op to bypass all perms, which is very sad because it's probably the best jetpack plugin that is out atm. We're probably gonna have to go back to using fly until this gets figured out.

**Comment by dcsepy01** [comment]
Version: 1.18.2
Server; Purpur
Using LuckPerms, SuperiorSkyblock2

Same issue here.

**Comment by minecraft-dripdrop** [comment]
same

**Comment by adi-itgg** [comment]
sorry guys too late, i found the problem, this is cause the player not updated from my plugin.
